version: "3.8"
services: 
  php-converter-api: 
    container_name: php-converter-api
    build: 
      context: ./converter-api
      target: php-converter-api
    expose: 
      - 9000
    volumes: 
      - ./converter-api:/usr/src/app
      - ./converter-api/public:/usr/src/app/public
    environment: 
      APP_NAME: Laravel
      APP_ENV: dev
      APP_KEY: base64:XfJMEWY4Y00O7TNw0oI9ND+1ijwiXu3r1m0NOZyJyp8=
      APP_DEBUG: true
      APP_URL: http://localhost:8000
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      QUEUE_CONNECTION: database
    depends_on: 
      - db
    networks: 
      - app_network
  
  nginx-converter-api: 
    container_name: nginx-converter-api
    build: 
      context: ./converter-api
      target: nginx-converter-api
    volumes: 
      - ./converter-api/public:/usr/src/app/public
    ports: 
      - 8000:80
    depends_on: 
      - php-converter-api
    environment: 
      NGINX_FPM_HOST: php-converter-api
      NGINX_ROOT: /usr/src/app/public
    networks: 
      - app_network

  db: 
    image: postgres:15
    container_name: postgres-db-easy-youtu
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: 
      - db:/var/lib/postgresql/data
    networks: 
      - app_network

  pgadmin: 
    image: dpage/pgadmin4
    container_name: pgadmin-easy-youtu
    restart: always
    ports: 
      - "8888:80"
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes: 
      - pgadmin:/var/lib/pgadmin*

networks: 
  app_network: 
    driver: bridge

volumes: 
  db: 
    external: true
  pgadmin: 
    external: true